# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.18 is version 38
loaderVersion="[38,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/nuggylib/naughty-monkeys/issues"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
modId="naughtymonkeys"
version="1.18.1-0.0.0.0"
displayName="Naughty Monkeys"
description='''
  A mod featuring poo-throwing masters of mischief
  '''

[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.18]"
ordering="NONE"
side="BOTH"